animals = ['bear', 'python','peacock','kangaroo','whale','platypus']

print "1-",animals[1]
print "2-",animals[3-1]
print "3-",animals[1-1]
print "4-",animals[3]
print "5-",animals[5-1]
print "6-",animals[2]
print "7-",animals[6-1]
print "8-",animals[4]